### ISSUE TITLE
<Input /> does not work inside a <Tab>

### ISSUE THREAD

**Issue by SumitBando** [Oli8/spaper#15]
This is due to _tabs.scss: line 9:
.tabs input {
    display: none;
}

Sample:
<div class="form-group">
	<Input placeholder="Works" label="Input" />
</div>

<Tabs>
	<Tab label="Registration">
<div class="form-group">
	<Input placeholder="Does not work" label="Input" />
</div>    
  </Tab>
</Tabs>

**Comment by SumitBando** [comment]
This can be overridden in the using component with
<style>
	:global(.tabs input) {
		display: block;
	}
</style>
However, other styles from the Tabs seems to be leaking into the <Input> component, leading to alignment issues

**Comment by Oli8** [comment]
> This can be overridden in the using component with
> 
> <style> :global(.tabs input) { display: block; } </style>
> However, other styles from the Tabs seems to be leaking into the component, leading to alignment issues

Hey @SumitBando, could you describe those alignment issues or provide a screenshot ?  
I'll add the fix regarding inputs display in the next release, thanks for reporting it.

**Comment by Oli8** [comment]
Fixed in v0.2.5
