### ISSUE TITLE
Burnt toast

### ISSUE THREAD

**Issue by pitininja** [Oli8/spaper#23]
Hello sir,

I've found a glitch with the Toast component on the demo website. On [this page](https://oli8.github.io/spaper/#/components/Toast), when I click the "Go" button it opens the Toast well, but then I can't click on the navigation buttons no more (in the main navigation menu).

I guess it has something to do with the `paper-toast-container` div that would prevent reaching the nav bar?

I'm on FIrefox 78.15.0esr, also tested on Brave 1.33.106.

Best regards

**Comment by Oli8** [comment]
Hey @pitininja,

Yes we actually caught that glitch right after the release, there's already a fix soon to be merged (https://github.com/Oli8/spaper/pull/22).
Thanks for the feedback nonetheless.

Cheers

**Comment by Oli8** [comment]
Fixed in v0.2.6

**Comment by Bergamof** [comment]
Stil an issue.
If enough notifications are displayed, the toast container "masks" the page contnent, making it impossible to click the button, for example

![image](https://user-images.githubusercontent.com/21084447/150605658-6f938297-ff4f-4d93-b962-6269593af390.png)

**Comment by Oli8** [comment]
That's right, I'll look that up

**Comment by Bergamof** [comment]
I'm no specialist of CSS, but if that can help, I found something that seems to resolve the issue :
```css
.paper-toast-container {
    overflow: visible !important;
    height: 0 !important;
    padding: 0 !important;
}
```
