### ISSUE TITLE
Using native HTML progress element for <Progress> component

### ISSUE THREAD

**Issue by 416d72** [Oli8/spaper#37]
## Hello
First off, huge thanks for your amazing work.

Wouldn't it be better to use the [native progress element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) instead of a simple `div`

**Comment by Oli8** [comment]
Hey, thanks !

Well I thought so too making the component but that's not how it was made in papercss :man_shrugging:  
Also note that there is an element for the container and one for the progress bar.
But yeah that would def be better and might be done down the road.
