### ISSUE TITLE
Form Component missing types

### ISSUE THREAD

**Issue by KevsRepos** [Oli8/spaper#48]
[Issue]
The `Form.svelte` component is missing types, see Image:

![image](https://user-images.githubusercontent.com/11198691/163460524-3f9f67c7-b0a3-4e0a-8307-d2c14de7ac33.png)

I was able to fix that locally by adding `extends SvelteComponentTyped<FormProps, FormEvents, FormSlots>` to `export default class Form` inside the npm module in the `Form.svelte.dt.ts` file. Though these files seem to be auto generated as they dont appear in the actual source code. How to fix this?

**Comment by Oli8** [comment]
Seems like the `d.ts` is not properly generated when the component has no `script` tag (svelte-kit bug?)
I'll update the `Form.svelte.dt.ts` in the next release, thanks for the report and the troubleshooting.

**Comment by Oli8** [comment]
Fixed in [v0.7.6](https://github.com/Oli8/spaper/releases/tag/v0.7.6)
